/* Patch the CI-generated Android project (M3). Because android/ is not committed
 * (it's regenerated by `npx cap add android` in the workflow), the manifest/label
 * customizations live here and are applied right before the Gradle build:
 *   - location permissions (required by @capacitor/geolocation for runtime GPS),
 *   - WAKE_LOCK (screen wake-lock while navigating),
 *   - a Hebrew launcher label.
 * Idempotent: safe to run repeatedly. */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';

const MANIFEST = 'android/app/src/main/AndroidManifest.xml';
const STRINGS = 'android/app/src/main/res/values/strings.xml';

if (!existsSync(MANIFEST)) {
  console.error(`${MANIFEST} not found — run "npx cap add android" first.`);
  process.exit(1);
}

let m = readFileSync(MANIFEST, 'utf8');
const perms = [
  'android.permission.ACCESS_COARSE_LOCATION',
  'android.permission.ACCESS_FINE_LOCATION',
  'android.permission.WAKE_LOCK',
];
const lines = perms
  .filter((p) => !m.includes(p))
  .map((p) => `    <uses-permission android:name="${p}" />`)
  .join('\n');

if (lines) {
  // Insert the permissions just before the <application> element.
  m = m.replace(/(\s*)<application/, `\n${lines}$1<application`);
  writeFileSync(MANIFEST, m);
  console.log('✓ added permissions:\n' + lines);
} else {
  console.log('✓ permissions already present');
}

// Hebrew launcher label.
if (existsSync(STRINGS)) {
  let s = readFileSync(STRINGS, 'utf8');
  s = s
    .replace(/(<string name="app_name">)[^<]*(<\/string>)/, '$1ניווט ימי$2')
    .replace(/(<string name="title_activity_main">)[^<]*(<\/string>)/, '$1ניווט ימי$2');
  writeFileSync(STRINGS, s);
  console.log('✓ set Hebrew launcher label');
}
